### ISSUE TITLE
Prevent empty files from being uploaded to effis

### ISSUE THREAD

**Issue by Sharp-Eyes** [Eludris/effis#2]
In my infinite intelligence, *I decided to do some testing* and found out that you can store empty files on effis. Since this is rather pointless and just takes up needless space (though ofc very little), I propose we disallow this altogether.

**Comment by EnokiUN** [comment]
did you **decide** to do that testing tho :pepehmm:

**Comment by Sharp-Eyes** [comment]
*yes*

**Comment by EnokiUN** [comment]
> _yes_

ok :+1:

**Comment by MaskDuck** [comment]
> In my infinite intelligence, _I decided to do some testing_ and found out that you can store empty files on effis. Since this is rather pointless and just takes up needless space (though ofc very little), I propose we disallow this altogether.

I propose no.

**Comment by EnokiUN** [comment]
> > In my infinite intelligence, _I decided to do some testing_ and found out that you can store empty files on effis. Since this is rather pointless and just takes up needless space (though ofc very little), I propose we disallow this altogether.
> 
> I propose no.

This comment has changed the issues status from "probably good idea" to a "must do"

**Comment by MaskDuck** [comment]
> > > In my infinite intelligence, _I decided to do some testing_ and found out that you can store empty files on effis. Since this is rather pointless and just takes up needless space (though ofc very little), I propose we disallow this altogether.
> > 
> > 
> > I propose no.
> 
> This comment has changed the issues status from "probably good idea" to a "must do"

why
